[package]
name = "mareto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12"
rfd = "0.14"
tokio = { version = "1.37", features = ["fs"] }